CREATE TABLE t_user (
i_user INT UNSIGNED AUTO_INCREMENT,
PRIMARY KEY(i_user),
uid VARCHAR(20) UNIQUE NOT NULL,
upw VARCHAR(30) NOT NULL,
nm VARCHAR(5) NOT NULL,
tel VARCHAR(12) NOT NULL,
addr VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE t_board (
i_board INT UNSIGNED AUTO_INCREMENT,
PRIMARY KEY(i_board),
i_user INT UNSIGNED NOT NULL,
title VARCHAR(150) NOT NULL,
ctnt VARCHAR(2000) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
files VARCHAR(100) DEFAULT NULL,
hit INT UNSIGNED NOT NULL DEFAULT 0,
liked INT UNSIGNED NOT NULL DEFAULT 0,
FOREIGN KEY (i_user) REFERENCES t_user(i_user)
);

show global variables like 'local_infile';

CREATE TABLE IF NOT EXISTS `ZIPCODE` (
`ZIP_NO` VARCHAR(5) NULL COMMENT '우편번호',
`SIDO` VARCHAR(20) NULL COMMENT '시도',
`SIDO_ENG` VARCHAR(40) NULL COMMENT '시도(영문)',
`SIGUNGU` VARCHAR(20) NULL COMMENT '시군구',
`SIGUNGU_ENG` VARCHAR(40) NULL COMMENT '시군구(영문)',
`EUPMYUN` VARCHAR(20) NULL COMMENT '읍면',
`EUPMYUN_ENG` VARCHAR(40) NULL COMMENT '읍면(영문)',
`DORO_CD` VARCHAR(12) NULL COMMENT '도로명코드',
`DORO` VARCHAR(80) NULL COMMENT '도로명',
`DORO_ENG` VARCHAR(80) NULL COMMENT '도로명(영문)',
`UNDERGROUND_YN` CHAR(1) NULL COMMENT '지하여부',
`BUILD_NO1` DECIMAL(5,0) NULL COMMENT '건물번호본번',
`BUILD_NO2` DECIMAL(5,0) NULL COMMENT '건물번호부번',
`BUILD_NO_MANAGE_NO` VARCHAR(25) NULL COMMENT '건물관리번호',
`DARYANG_NM` VARCHAR(40) NULL COMMENT '다량배달처명',
`BUILD_NM` VARCHAR(200) NULL COMMENT '시군구용건물명',
`DONG_CD` VARCHAR(10) NULL COMMENT '법정동코드',
`DONG_NM` VARCHAR(20) NULL COMMENT '법정동명',
`RI` VARCHAR(20) NULL COMMENT '리명',
`H_DONG_NM` VARCHAR(40) NULL COMMENT '행정동명',
`SAN_YN` VARCHAR(1) NULL COMMENT '산여부',
`ZIBUN1` DECIMAL(4,0) NULL COMMENT '지번본번',
`EUPMYUN_DONG_SN` VARCHAR(2) NULL COMMENT '읍면동일련번호',
`ZIBUN2` DECIMAL(4,0) NULL COMMENT '지번부번' ,
`ZIP_NO_OLD` VARCHAR(4) NULL COMMENT '구우편번호' ,
`ZIP_SN` VARCHAR(2) NULL COMMENT '우편일련번호'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

LOAD DATA LOCAL INFILE "E:/PHP/zipcode_DB/17.txt" INTO TABLE zipcode CHARACTER SET 'utf8' FIELDS TERMINATED BY '|' IGNORE 1 LINES;